{
 "title": "SwingSight Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total balls hit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_balls_hit{job=\"swingsight_app\"}"
    }
   ]
  },
  {
   "title": "Last ball data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "angle_of_departure{job=\"swingsight_app\"}",
     "legendFormat": "Angle"
    },
    {
     "expr": "velocity_at_departure{job=\"swingsight_app\"}",
     "legendFormat": "Velocity"
    },
    {
     "expr": "projected_yardage{job=\"swingsight_app\"}",
     "legendFormat": "Yardage"
    },
    {
     "expr": "projected_zone{job=\"swingsight_app\"}",
     "legendFormat": "Zone"
    }
   ]
  },
  {
   "title": "Zone counts",
   "type": "stat",
   "description": "Golf ball counts in each zone",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_zone_1{job=\"swingsight_app\"}",
     "legendFormat": "Zone 1"
    },
    {
     "expr": "count_zone_2{job=\"swingsight_app\"}",
     "legendFormat": "Zone 2"
    },
    {
     "expr": "count_zone_3{job=\"swingsight_app\"}",
     "legendFormat": "Zone 3"
    }
   ]
  }
 ]
}